theme:
  name: material
  palette:
    primary: teal
  logo: img/favicon_io/favicon-32x32.png
  favicon: img/favicon_io/favicon.ico
  # icon:
    # repo: fontawesome/brands/gitlab
site_name: Netts
repo_name: alan-turing-institute/netspy
repo_url: https://github.com/alan-turing-institute/netspy
# icon:
#   repo: fontawesome/brands/github-alt

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - mkdocs-click

nav:
  - Overview: index.md
  - Getting Started: install.md
  - Usage:
      - Overview: basic_usage.md
      - Configuration: configuration.md
      - CLI: cli.md
  - Pipeline: pipeline.md