theme:
  name: material
site_name: Netspy
repo_name: alan-turing-institute/netspy
repo_url: https://github.com/alan-turing-institute/netspy
icon:
  repo: fontawesome/brands/github-alt

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - mkdocs-click

nav:
  - Netspy: index.md
  - Usage: cli.md
  - Configuration: configuration.md