theme:
  name: material
site_name: Netts
repo_name: alan-turing-institute/netts
repo_url: https://github.com/alan-turing-institute/netts
icon:
  repo: fontawesome/brands/github-alt

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - mkdocs-click

nav:
  - Netts: index.md
  - Getting Started: install.md
  - Usage:
      - Overview: basic_usage.md
      - Configuration: configuration.md
      - CLI: cli.md
