theme:
  name: material
site_name: Netspy
repo_name: alan-turing-institute/netspy
repo_url: https://github.com/alan-turing-institute/netspy
icon:
  repo: fontawesome/brands/github-alt

nav:
  - Netspy: index.md
