theme:
  name: material
  favicon: /Users/CN/Documents/Projects/Cambridge/from_turing/netspy/docs/docs/img/favicon_ico/favicon-16x16.png
  logo: /Users/CN/Documents/Projects/Cambridge/from_turing/netspy/docs/docs/img/favicon_ico/favicon-16x16.png
  palette:
    primary: teal
site_name: Netts
repo_name: alan-turing-institute/netspy
repo_url: https://github.com/alan-turing-institute/netspy
icon:
  repo: fontawesome/brands/github-alt

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - mkdocs-click

nav:
  - Overview: index.md
  - Getting Started: install.md
  - Usage:
      - Overview: basic_usage.md
      - Configuration: configuration.md
      - CLI: cli.md
  - Pipeline: pipeline.md