---
name: check-downloads-on-cron

on:
  schedule:
    # Run on the first of the month at midnight
    - cron: '0 0 1 * *'

jobs:

  check-downloads:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Bootstrap poetry
      shell: bash
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.4.0

    - name: Configure poetry
      shell: bash
      run: |
        python -m poetry config virtualenvs.in-project true
        python -m poetry config virtualenvs.create true

    - name: Set up cache
      uses: actions/cache@v2
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-3.8-${{ hashFiles('**/poetry.lock') }}

    - name: Install netts
      shell: bash
      run: |
        python -m poetry install

    - name: Check downloads work
      shell: bash
      run: |
        python -m poetry run netts install
