name: markdown-lint
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
      - '.mdlrc'
      - '.mdl.rb'
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
      fail-fast: false
    env:
      # Set the location of netspy dependencies
      NETSPY_DIR: '.dependencies'

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: MarkdownLint mdl Action
      uses: actionshub/markdownlint@2.0.2
