name: test-cache
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Bootstrap poetry
      shell: bash
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Configure poetry
      shell: bash
      run: |
        python -m poetry config virtualenvs.in-project true
        python -m poetry config virtualenvs.create true

    - name: Set up cache
      uses: actions/cache@v2
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    # - name: Ensure cache is healthy
    #   if: steps.cache.outputs.cache-hit == 'true'
    #   shell: bash
    #   run: timeout 10s python -m poetry run pip --version || rm -rf .venv

    - name: show venv
      shell: bash
      run: | 
        ls .venv
        pwd

    - name: Install dependencies
      run: |
        poetry env use 3.7
        poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Display Python version
      run: poetry run python -c "import sys; print(sys.version); import netspy"